from django.urls import path

from .views import (
    DiscoverMoviesView,
    DiscoverTvShowsView,
    MovieDetailsView,
    MovieCategoriesView,
    NowPlayingMoviesView,
    PersonDetailsView,
    SearchMoviesView,
    PopularActorsView,
    PopularDirectorsView,
    PopularMoviesView,
    TopRatedMoviesView,
    PopularTvShowsView,
    TrendingMoviesView,
    TrendingPeopleView,
    TvCategoriesView,
    TvShowDetailsView,
    UpcomingMoviesView,
)

urlpatterns = [
    path('search', SearchMoviesView.as_view(), name='movies-search'),
    path('movies/categories', MovieCategoriesView.as_view(), name='movies-categories'),
    path('tv-shows/categories', TvCategoriesView.as_view(), name='tv-shows-categories'),
    path('movies/trending', TrendingMoviesView.as_view(), name='movies-trending'),
    path('people/trending', TrendingPeopleView.as_view(), name='people-trending'),
    path('movies/discover', DiscoverMoviesView.as_view(), name='movies-discover'),
    path('tv-shows/discover', DiscoverTvShowsView.as_view(), name='tv-shows-discover'),
    path('movies/popular', PopularMoviesView.as_view(), name='movies-popular'),
    path('movies/top-rated', TopRatedMoviesView.as_view(), name='movies-top-rated'),
    path('movies/now-playing', NowPlayingMoviesView.as_view(), name='movies-now-playing'),
    path('movies/upcoming', UpcomingMoviesView.as_view(), name='movies-upcoming'),
    path('movies/<str:movie_id>', MovieDetailsView.as_view(), name='movie-details'),
    path('tv-shows/popular', PopularTvShowsView.as_view(), name='tv-shows-popular'),
    path('tv-shows/<str:tv_show_id>', TvShowDetailsView.as_view(), name='tv-show-details'),
    path('people/actors', PopularActorsView.as_view(), name='people-actors'),
    path('people/directors', PopularDirectorsView.as_view(), name='people-directors'),
    path('people/<str:person_id>', PersonDetailsView.as_view(), name='person-details'),
]
